stackTestsDir = Stack/
linkedListTestsDir = LinkedList/

stackTestObjects = install_stack0.0_test clean_stack0.0_test run_stack0.0_test install_stack1.0_test clean_stack1.0_test run_stack1.0_test
linkedListTestObjects = install_linkedlist0.0_test clean_linkedlist0.0_test run_linkedlist0.0_test

$(stackTestObjects):
	make $@ -C  $(stackTestsDir)

$(linkedListTestObjects):
	make $@ -C $(linkedListTestsDir)

