
install_linkedlist0.0_test:
	make install_linkedlist0.0_test -C linkedList0.0

run_linkedlist0.0_test:
	make run_linkedlist0.0_test -C linkedList0.0

clean_linkedlist0.0_test:
	make clean_linkedlist0.0_test -C linkedList0.0

