stack0.0 = Stack/stack0.0
stack1.0 = Stack/stack1.0
linkedList0.0 = LinkedList/linkedList0.0

%stack0.0:
	make $@ -C  $(stack0.0)

%stack1.0:
	make $@ -C  $(stack1.0)

%linkedlist0.0:
	make $@ -C $(linkedList0.0)

