
install_stack0.0:
	make install_stack0.0 -C  Stack/stack0.0

clean_stack0.0:
	make clean_stack0.0 -C  Stack/stack0.0

install_stack1.0:
	make install_stack1.0 -C  Stack/stack1.0

clean_stack1.0:
	make clean_stack1.0 -C  Stack/stack1.0

install_linkedlist0.0:
	make install_linkedlist0.0 -C LinkedList/linkedList0.0

clean_linkedlist0.0:
	make clean_linkedlist0.0 -C LinkedList/linkedList0.0

