
install_stack0.0_test:
	make install_stack0.0_test -C  tests/Stack/stack0.0

run_stack0.0_test:
	make run_stack0.0_test -C  tests/Stack/stack0.0

clean_stack0.0_test:
	make clean_stack0.0_test -C  tests/Stack/stack0.0

