stackDir = Stack/
linkedListDir = LinkedList/

stackObjects = install_stack0.0 install_stack1.0 clean_stack0.0 clean_stack1.0
linkedListObjects = install_linkedlist0.0 clean_linkedlist0.0

$(stackObjects):
	make $@ -C  $(stackDir)

$(linkedListObjects):
	make $@ -C $(linkedListDir)
