
install_stack0.0:
	make install_stack0.0 -C  stack0.0

clean_stack0.0:
	make clean_stack0.0 -C  stack0.0
	
install_stack1.0:
	make install_stack1.0 -C  stack1.0

clean_stack1.0:
	make clean_stack1.0 -C  stack1.0
	
