
install_stack0.0:
	make install_stack0.0 -C  lib/Stack/stack0.0

clean_stack0.0:
	make clean_stack0.0 -C  lib/Stack/stack0.0

install_linkedlist0.0:
	make install_linkedlist0.0 -C lib/LinkedList/linkedList0.0

clean_linkedlist0.0:
	make clean_linkedlist0.0 -C lib/LinkedList/linkedList0.0

install_stack0.0_test:
	make install_stack0.0_test -C  tests/Stack/stack0.0

run_stack0.0_test:
	make run_stack0.0_test -C  tests/Stack/stack0.0

clean_stack0.0_test:
	make clean_stack0.0_test -C  tests/Stack/stack0.0

install_linkedlist0.0_test:
	make install_linkedlist0.0_test -C tests/LinkedList/linkedList0.0

run_linkedlist0.0_test:
	make run_linkedlist0.0_test -C tests/LinkedList/linkedList0.0

clean_linkedlist0.0_test:
	make clean_linkedlist0.0_test -C tests/LinkedList/linkedList0.0

